### ISSUE TITLE
sensor.ferroamp_external_energy_produced is not strictly increasing

### ISSUE THREAD

**Issue by jonasbkarlsson** [henricm/ha-ferroamp#126]
The `sensor.ferroamp_external_energy_produced` has suddenly started to oscillate between two values (723.4 and 723.5). It makes the Energy Dashboard in HA look weird.
![image](https://user-images.githubusercontent.com/12384363/154234961-05caa786-3c69-4cb0-8b8e-23f313dbdc2e.png)
Maybe this is a bug in the EnergyHub, but would it be possible for the integration to ensure that the values delivered are strictly increasing?

Maybe not so easy to achieve, without causing other problems...

**Comment by argoyle** [comment]
Hmmm, thought I had fixed that one already.

**Comment by argoyle** [comment]
Can you check the events from the EnergyHub via a MQTT client and see if the values are actually oscillating?

**Comment by argoyle** [comment]
It's the `wextprodq` attribute you are interested in

**Comment by jonasbkarlsson** [comment]
The oscillations have now stopped, since I'm now exporting to the grid. Should have checked the EnergyHub before. However, I also have Node-RED/Grafana, and I can see the same strange results there. See the blue (Exported to grid) during the last night. So it's quite clear that the data from the EnergyHub has been strange.
![image](https://user-images.githubusercontent.com/12384363/154264106-e6283d60-45fa-49b2-a478-9d93c112115a.png)

**Comment by argoyle** [comment]
I misrembered regarding fixing the issue though, that was just for the "regular" energy-sensors, not the ThreePhase sensors. I'll make the same change there later. That will make the value strictly increasing.

**Comment by argoyle** [comment]
@jonasbkarlsson Please have a look at the #129 It should solve your problem for next time.
