### ISSUE TITLE
Ampere on each phase

### ISSUE THREAD

**Issue by riksarchen** [henricm/ha-ferroamp#158]
Hello
Is it possible to add ampere on each phase sensors? I assume it’s available through the api? 

Thanks

**Comment by argoyle** [comment]
Each of the current-sensors have each phase as an attribute 
<img width="399" alt="image" src="https://user-images.githubusercontent.com/328334/164913761-f314e6cf-586e-460b-87be-0b029022978c.png">

**Comment by riksarchen** [comment]
Oh. Sorry about that. Case closed

**Comment by argoyle** [comment]
No need to be sorry. 😁
