### ISSUE TITLE
ferroamp_control_status sensor wrong data

### ISSUE THREAD

**Issue by mipe79** [henricm/ha-ferroamp#239]
The sensor "**ferroamp_control_status**" seems to be able to have wrong data.
I could see that it has the state "extapiversion" in the history.

**Comment by argoyle** [comment]
That is correct, it's the command we send to get the version back from the Energy hub.

**Comment by mipe79** [comment]
Shouldn't this sensor has data "auto/charge/discharge"?

**Comment by argoyle** [comment]
The sensor has the last command sent and result received from the Energy hub. `extapiversion` is one such available command.

**Comment by mipe79** [comment]
Ok, I see.
