### ISSUE TITLE
Sensor Cost?

### ISSUE THREAD

**Issue by bj00rn** [henricm/ha-ferroamp#283]
What are these sensors?

<img width="469" alt="image" src="https://user-images.githubusercontent.com/10961167/213160014-f8d87b47-6531-4ca1-b46c-032ab18a771e.png">

sensor.energyhub_14_external_energy_consumed_cost
sensor.energyhub_14_external_energy_consumed_cost

Can't find any references in source for these.

**Comment by robinostlund** [comment]
They are created by the energy integration in ha so not related to this integration 😊

**Comment by bj00rn** [comment]
> They are created by the energy integration in ha so not related to this integration 😊

Ok I see, nothing to worry about then

**Comment by argoyle** [comment]
Love it when the community solves stuff before I even have seen it. 😆 ❤️

**Comment by bj00rn** [comment]
> Love it when the community solves stuff before I even have seen it. 😆 ❤️

The naming of the sensor is a bit misleading. One gets the impression that it belongs to this integration.  But i guess that's out of our control 🤷

**Comment by argoyle** [comment]
Yep, that's HA long term statistics/energy dashboard thingie doing it's magic.
