### ISSUE TITLE
Battery entities not able to choose in Energy Dashboard 

### ISSUE THREAD

**Issue by andreasropel** [henricm/ha-ferroamp#291]
Hi. 

I am not able to setup these two in energy dashboard. They don’t even show up as entities in the list when choosing battery consumption or production. Are they defined in correct way? 

```
Battery Energy Produced
Battery Energy Consumed
```

TIA 
—Andreas

**Comment by argoyle** [comment]
Hmmm, that's strange. I have them in mine. Can you check the statistics-tav in Developer Tools and see if there is some problem with them perhaps?

**Comment by andreasropel** [comment]
To me they looks ok! 
thanks for quick reply. 


![394D72B2-D970-4803-B0EB-C075B158BB99](https://user-images.githubusercontent.com/54886635/215974133-6c384ef1-ba99-41c6-a86f-0dafd836ae23.png)

**Comment by argoyle** [comment]
That's the information the Energy-thingie uses

**Comment by andreasropel** [comment]
You mean this? 

![EFA8D145-D333-4817-A381-FF6DA469596A](https://user-images.githubusercontent.com/54886635/215975045-0888b0ee-597d-4273-86e9-571bdb9c019a.jpeg)

**Comment by andreasropel** [comment]
I found the problem. Need to include them in recorder of course!! Thanks for guidance

**Comment by argoyle** [comment]
No, the statistics-tab at the right side here 😄 
<img width="689" alt="image" src="https://user-images.githubusercontent.com/328334/215975497-318dd75d-3c77-49ba-9a64-99606cde555b.png">

But good that you found the problem.
