### ISSUE TITLE
Non-numeric value

### ISSUE THREAD

**Issue by argoyle** [henricm/ha-ferroamp#292]
Just noticed this in my log:
```
Sensor sensor.ferroamp_available_rms_current_for_load_balancing has device class current, state class measurement and unit A thus indicating it has a numeric value; however, it has the non-numeric value: unknown (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
```

**Comment by robinostlund** [comment]
I also have this, do you think this is related to upgrade of the hub @argoyle ? i am on version 5.2.6

**Comment by argoyle** [comment]
I thinks it's something new in HA since 2022.2. I'll see if I can solve it somehow when I have time.

**Comment by argoyle** [comment]
As far as I have understood those three sensors needs to be configured in the hub before it's going to send values for them. Perhaps a better solution would be to not create those if no values comes from the hub?

**Comment by robinostlund** [comment]
@argoyle agree, if not exists = skip or something :)
