### ISSUE TITLE
Entity id already exists error logging

### ISSUE THREAD

**Issue by henricm** [henricm/ha-ferroamp#3]
After first startup of this integration, entities are added even though they are already in home assistant, which results in the logging below:

`Entity id already exists - ignoring: sensor.ferroamp_sso_pv_string_power`

I guess we should check if entity already is in home assistant before calling `async_add_entities`?

**Comment by argoyle** [comment]
This would be closed by #10

**Comment by argoyle** [comment]
Closing now that #10 is merged
