### ISSUE TITLE
Issue with v1.10.2

### ISSUE THREAD

**Issue by u1malmberg** [henricm/ha-ferroamp#318]
I installed latest version two days ago and the fix for v1.10.2 ([743cb44](https://github.com/henricm/ha-ferroamp/commit/743cb440ed280e5adda2f699f2f2c78d6b819785))  is causing issues with the statistics. 

For two days the daily production utility "daily" meter have been completely off.  Today showing ~5MWh instead of 40-50kWh. 

Checking on the data I can see both days I have had one value reported from Ferroamp that have been off by 18% and 22%, both happening within 15mins around 1400hrs both days.  

Attached image shows total energy produced reported around 27MWh, then there is one erroneous at 22MWh, from there on the daily is then at 4.7MWh rather than the ~45kWh.

<img width="1369" alt="image" src="https://user-images.githubusercontent.com/73966842/229361005-aa9e640d-8611-4ec1-8ccd-8a670abe830c.png">

If this fix is to handle an actual reset, why not block down to 90% rather than the current 10% (also it appears to be actually less than 10%).  A reset is 100% after all! :) 

So, the assumption that wrong data only is 10% less is not accurate.

**Comment by robinostlund** [comment]
I also noticed this yesterday when i restarted by hub 😊

**Comment by argoyle** [comment]
Hmmm, maybe we should revert that change @henricm ? What versions do you guys have on your EnergyHubs? Just trying to find some kind of pattern here on why/when this is happening.

**Comment by u1malmberg** [comment]
I am running 5.0.3 if that makes a difference.  Not sure where these erroneous values comes from as it is just one in the serie, then back to correct values again.  There used to be similar issues before it was set to "total_Increasing", but that was fixed more than a year ago and it has worked like a charm ever since.

It would not be so bad if it did not mess up the daily, monthly, yearly aggregates.

**Comment by henricm** [comment]
How does it continue? Will EH continue to report 22 MWh and increasing from there or does it go back to 27 MWh?

Could you post more data and possibly also how this looks in energy cloud?
When sensors are affected?

Home assistant uses 10% margin when trying to determine if there has been a reset or if there are error values for total-increasing sensors, so that's the reason for using the same. 
Also, even if an actual reset happens it may take time before a system is back up again. And the counters may have moved during this time so I don't think we can use eg 90%. 

If we should change this back it would be good to know more details when this happens and the nature of the incorrect values. Rather than a % maybe we may also need to use a time frame?

**Comment by argoyle** [comment]
Maybe we could ignore outliers somehow?

**Comment by u1malmberg** [comment]
As mentioned earlier, not sure why it occurred, never actually seen it before, although that does not mean much as you seldom look at the actual data -- row by row.  But, at least in these two instances, it was just one value that stood out, before and after the series is correct.  

<img width="1270" alt="image" src="https://user-images.githubusercontent.com/73966842/229371508-f3a7758e-dcc3-4f1f-bbbf-503934efb810.png">

**Comment by henricm** [comment]
Would be good to know how "wrong" the data could be. I guess ferroamp has no clue about this issue?

**Comment by henricm** [comment]
> Maybe we could ignore outliers somehow?

Is it doable to determine this scenario where a value is off a few seconds - and ignore it in that case? We do some average calculation already for values entering in between the configured fetch interval, right? Maybe it can bee hooked in there somehow?

**Comment by u1malmberg** [comment]
hmm, I cannot see any traces of this in the reports in FA portal -- although they are on a fairly high level.  

Just looked at the dataset from 1st of jan this year up until today, exported it into csv and these two instances from today and yesterday are the only entries that are "off".  well.. based on sorting all the rows and checking from lowest ... just these two.  

Strange, I mean what are the odds!?  only two errors this year are since after I updated the integration.  I did update from 1.9-ish!? not sure exact "from" version (is it possible to check in HA somewhere!?), could it be one of the other patches that somehow could mess up the data? 

Also, last two days have been the sunniest this year :) , so I guess we cannot rule out that the errors from FA could be more frequent under heavy load or something.

**Comment by henricm** [comment]
We ignored all lower values so I guess that's why you don't see any of this before updating to latest.

**Comment by henricm** [comment]
A quick fix for this particular case would be to change the 10 % limit to 25 % instead and hope that's about how wrong the data can get.
I don't think I've seen this issue except in cases where there has been some issue with my EH. I recently got the SD card replaced for example, resetting some (not all) counters.

**Comment by robinostlund** [comment]
I am running 5.3.2. I will doublecheck tomorrow but i think it was showing 0 at one point after reboot of the hub

**Comment by robinostlund** [comment]
![image](https://user-images.githubusercontent.com/12171819/229373252-be73a3f5-140c-40c5-b681-f1e4de7a7383.jpeg)

**Comment by argoyle** [comment]
> > Maybe we could ignore outliers somehow?
> 
> Is it doable to determine this scenario where a value is off a few seconds - and ignore it in that case? We do some average calculation already for values entering in between the configured fetch interval, right? Maybe it can bee hooked in there somehow?

I'm thinking we could have a sliding average of the last minute or so and compare with that?

**Comment by u1malmberg** [comment]
The big question is if to leave it also for tomorrow to see if I get the same results around 1400 again! 😃

**Comment by henricm** [comment]
> ![image](https://user-images.githubusercontent.com/12171819/229373252-be73a3f5-140c-40c5-b681-f1e4de7a7383.jpeg)

Thanks! Have you reported this to ferroamp? Doesn't look healthy.

**Comment by robinostlund** [comment]
@henricm haven't reported this to ferroamp, will do that now :)

**Comment by robinostlund** [comment]
Created a ticket to ferroamp now. Noticed that these issues only occur on data from SSO + ESO, not the hub itself.
<img width="1047" alt="Screenshot 2023-04-03 at 10 29 14" src="https://user-images.githubusercontent.com/12171819/229455915-6bd1cead-874b-4db2-968e-c286e0992d78.png">
<img width="927" alt="Screenshot 2023-04-03 at 10 34 15" src="https://user-images.githubusercontent.com/12171819/229455926-b3c05396-cda6-4b30-8e59-4af3ae1befc3.png">

**Comment by henricm** [comment]
> > > Maybe we could ignore outliers somehow?
> > 
> > 
> > Is it doable to determine this scenario where a value is off a few seconds - and ignore it in that case? We do some average calculation already for values entering in between the configured fetch interval, right? Maybe it can bee hooked in there somehow?
> 
> I'm thinking we could have a sliding average of the last minute or so and compare with that?

Maybe not work that well with the scenario @robinostlund is experiencing where values dropping to 0. I'm thinking that maybe this is happening to @u1malmberg too, but the average-calculation we do in between updates maybe hides this fact?

One idea could be to to max() of the x latest values. Then it will take a few updates before an actual reset is taken into account, but a few error values won't affect the sensor.

**Comment by robinostlund** [comment]
or should we just add a if >= 0 skip or something? As it seems to go to zero when it is rebooted? 😄

**Comment by argoyle** [comment]
> > > > Maybe we could ignore outliers somehow?
> > > 
> > > 
> > > Is it doable to determine this scenario where a value is off a few seconds - and ignore it in that case? We do some average calculation already for values entering in between the configured fetch interval, right? Maybe it can bee hooked in there somehow?
> > 
> > 
> > I'm thinking we could have a sliding average of the last minute or so and compare with that?
> 
> Maybe not work that well with the scenario @robinostlund is experiencing where values dropping to 0. I'm thinking that maybe this is happening to @u1malmberg too, but the average-calculation we do in between updates maybe hides this fact?
> 
> One idea could be to to max() of the x latest values. Then it will take a few updates before an actual reset is taken into account, but a few error values won't affect the sensor.

Not sure how that would be handled with regards to average values etc. I think I'm more inclined to do the skip 0-values as @robinostlund suggested. That is if the actual low value seen by @u1malmberg was 0 (it was averaged out in the graphs of course and not sure how to know what the actual value was).

**Comment by u1malmberg** [comment]
Was going to tell you that I did not receive any wrong data today around 1400 (as usual), but then it happened around 16:30-ish instead.     About the same "distance", ~20%, away from the correct values.  

@argoyle, I am not seeing 0 values, just 20%-ish off values. 

The 25% limit discussed above might work for me, but then again, since we do not know why the data is wrong, then we do not really know what the diff could be in the future... 

<img width="1299" alt="image" src="https://user-images.githubusercontent.com/73966842/229570974-b5972090-af38-45af-81cd-2129866f44c8.png">

**Comment by henricm** [comment]
> > > > > Maybe we could ignore outliers somehow?
> 
> > > > 
> 
> > > > 
> 
> > > > Is it doable to determine this scenario where a value is off a few seconds - and ignore it in that case? We do some average calculation already for values entering in between the configured fetch interval, right? Maybe it can bee hooked in there somehow?
> 
> > > 
> 
> > > 
> 
> > > I'm thinking we could have a sliding average of the last minute or so and compare with that?
> 
> > 
> 
> > Maybe not work that well with the scenario @robinostlund is experiencing where values dropping to 0. I'm thinking that maybe this is happening to @u1malmberg too, but the average-calculation we do in between updates maybe hides this fact?
> 
> > 
> 
> > One idea could be to to max() of the x latest values. Then it will take a few updates before an actual reset is taken into account, but a few error values won't affect the sensor.
> 
> 
> 
> Not sure how that would be handled with regards to average values etc. I think I'm more inclined to do the skip 0-values as @robinostlund suggested. That is if the actual low value seen by @u1malmberg was 0 (it was averaged out in the graphs of course and not sure how to know what the actual value was).

Maybe worth a try - if it's always 0-values that's causing this issue. Regardless this needs to be done in the average calc right? Since it's already too late if the incorrect values have been included in the average sum?

Otherwise I was thinking we could keep a list of the latest 10 or so values. Just as we keep values in between the configured update interval to do the average calc. And use Max instead of average for total-increasing energy counters which should make more sense than average calc. That could then also work if other types of junk values can appear.

But it will of course complicate things a bit 🙂.

**Comment by henricm** [comment]
> Was going to tell you that I did not receive any wrong data today around 1400 (as usual), but then it happened around 16:30-ish instead.     About the same "distance", ~20%, away from the correct values.  
> 
> 
> 
> @argoyle, I am not seeing 0 values, just 20%-ish off values. 
> 
> 
> 
> The 25% limit discussed above might work for me, but then again, since we do not know why the data is wrong, then we do not really know what the diff could be in the future... 
> 
> 
> 
> <img width="1299" alt="image" src="https://user-images.githubusercontent.com/73966842/229570974-b5972090-af38-45af-81cd-2129866f44c8.png">
> 
> 

You do not see all values that EH sends since the sensor in HA is only updated every 30 second but values from EH arrives more often than that. The values that arrives in between are collected and used in average calculation every 30 second (or the interval you've configured). To see all values maybe you could connect an mqtt explorer or if it's possible to enable more logging of mqtt messages in HA?

**Comment by robinostlund** [comment]
@henricm what version are you running? they did some changes regarding the measurement in latest version: https://support.ferroamp.com/en/support/solutions/articles/47001241579-software-release-5-3-2

**Comment by henricm** [comment]
@robinostlund I'm on 5.0.3

**Comment by henricm** [comment]
Closing. Please reopen or file new issue if the problem comes back.
