### ISSUE TITLE
Additional SSO Fault codes

### ISSUE THREAD

**Issue by bj00rn** [henricm/ha-ferroamp#361]
Found this on Ferroamp facebook group. Not sure where it came from originally though

![image](https://github.com/henricm/ha-ferroamp/assets/10961167/ee9d5e53-a4af-4461-905e-b36ab393430a)

**Comment by argoyle** [comment]
Nice! Could you create a PR for those?

**Comment by bj00rn** [comment]
> Nice! Could you create a PR for those?

I will have a look at it.

Maybe it would be nice to differentiate between errors and warning while i'm at it?

Im thinking in the lines
```
FAULT_CODES_SSO = [
    'ERROR_INTERNAL_VOLTAGE_UNBALANCE'
    ...
    'WARNING_POWERLIMITING',
]
```

**Comment by argoyle** [comment]
Sounds reasonable
