### ISSUE TITLE
EnergyHub DC Link Voltage state is zero

### ISSUE THREAD

**Issue by bj00rn** [henricm/ha-ferroamp#364]
Seems that the sensor state sums up to zero.

<img width="544" alt="image" src="https://github.com/henricm/ha-ferroamp/assets/10961167/373d0af8-9d10-4d6e-b7b9-beafa75e68bb">

Is this really the correct way to represent DC voltage? I have no domain knowledge here whatsoever here, it just appears to me that the current state value seems useless, especially when trying to correlate DC link voltage history with SSO fault codes.

Nominal DC link voltage is 760V (720-780V) according to specs, which leaves 380+380 within that range..

<img width="655" alt="image" src="https://github.com/henricm/ha-ferroamp/assets/10961167/0bddba86-00ce-417a-875f-67067db02962">

From the looks of it would seem that a useful way of summing up dc link voltage would be something like self._attr_native_value = int(abs(neg) / count + pos / count). Again, i have no domain knowledge here so maybe im wrong.

offending line:
https://github.com/henricm/ha-ferroamp/blob/56df5e9f542d0b4d9f843acd52ab5107cdcfd614/custom_components/ferroamp/sensor.py#L759

**Comment by argoyle** [comment]
No domain knowledge at my end either but I see how you're thinking. @danielolsson100 or @mickecamino perhaps knows more?

**Comment by danielolsson100** [comment]
@argoyle I have no clue in this matter since I am not using this value at all, I don't even store the history data in the DB for this sensor ;)

**Comment by jonasbkarlsson** [comment]
It should be `pos / count - neg / count`.

Also, it shouldn't be `int()`. Would be better to use something like `round(float(pos / count - neg / count), 2)`.

**Comment by mickecamino** [comment]
The value from Ferroamp is a floa, so it should be a float in the code:
![SSO-MQTT](https://github.com/henricm/ha-ferroamp/assets/12142651/599a73d9-70d0-44df-b86e-f0e415718466)

**Comment by argoyle** [comment]
> It should be `pos / count - neg / count`.
> 
> Also, it shouldn't be `int()`. Would be better to use something like `round(float(pos / count - neg / count), 2)`.

That would result in ~760 in the case @bj00rn had, right? Can someone provide a PR with those changes?

**Comment by mickecamino** [comment]
Hmmm, it seems that I looked at the wrong sensor, Here is the correct one:
![dclink-voltage](https://github.com/henricm/ha-ferroamp/assets/12142651/c699f642-85e5-414d-930f-a24fbeb4d0f9)

**Comment by bj00rn** [comment]
> > It should be `pos / count - neg / count`.
> > Also, it shouldn't be `int()`. Would be better to use something like `round(float(pos / count - neg / count), 2)`.
> 
> That would result in ~760 in the case @bj00rn had, right? Can someone provide a PR with those changes?


I can give it a shot

**Comment by bj00rn** [comment]
Works on my machine (TM) :-)

![Screenshot_20230709-133043](https://github.com/henricm/ha-ferroamp/assets/10961167/5252d691-77b8-4a3b-b617-a7e59d5e758f)
