### ISSUE TITLE
vscode devcontainer support?

### ISSUE THREAD

**Issue by bj00rn** [henricm/ha-ferroamp#371]
How about adding config for a vscode devcontainer for the project? devcontainers are friggin awesome

no changes are needed to the codebase, just some config files

See https://github.com/ludeeus/integration_blueprint

**Comment by argoyle** [comment]
Not a VSCode user myself but anything to make it easier for others to contribute is welcome. Please add a PR.

**Comment by bj00rn** [comment]
did a PR, adds the .vscode, .devcontainer folders with vscode specific stuff. Works like a charm
