### ISSUE TITLE
Entities in 1.14.0 shows too many decimals

### ISSUE THREAD

**Issue by pertakman** [henricm/ha-ferroamp#394]
Upgraded from 1.13.0 to 1.14.0 and noted that entities shows too many decimals. Given that Lovelace does not have an easy way to round off numbers I decided to revert to 1.13.0 and found that the numbers now come out rounded. Not sure whether this is considered a bug or simply a desired change of behavior, but I prefer the numbers rounded. :-)

**Comment by argoyle** [comment]
If you open the entity and then click the cogwheel you can change precision for each entity there.

**Comment by pertakman** [comment]
Thank you for that tip! It has slipped my new feature radar. Sounds like a great solution.
