### ISSUE TITLE
Hi and thanks for the very good follow-up :), MQTT had to be turned on in the local ferroamp from the supplier. Everything now seems to work.

### ISSUE THREAD

**Issue by Moogels** [henricm/ha-ferroamp#417]
Hi and thanks for the very good follow-up :), MQTT had to be turned on in the local ferroamp from the supplier. Everything now seems to work.

_Originally posted by @bopbrev in https://github.com/henricm/ha-ferroamp/issues/72#issuecomment-916988244_

**Comment by Moogels** [comment]
Hi, who did you contact? Is it possible to do it yourself?

**Comment by argoyle** [comment]
You need to contact Ferroamp support here: https://support.ferroamp.com/sv-SE/support/tickets/new

**Comment by Moogels** [comment]
I have contact ferroamp support, and I think that it's working when I look at the log from MQTT explorer? 
But not in homeassistant  : /
Could you please check my screen shots for any faulty settings? :  

![addon i homeassistant customize](https://github.com/henricm/ha-ferroamp/assets/33594610/20289e6f-370b-4e33-9733-4e84029c5e6f)
![Hacs integration endast 2 sensorer](https://github.com/henricm/ha-ferroamp/assets/33594610/af5c5ca5-c92a-472f-962a-e9da980a30f3)
![Log Mosquitto broker](https://github.com/henricm/ha-ferroamp/assets/33594610/d651bbe7-13ff-42ac-8618-0e3167b85150)
![mosquitto conffil samba share](https://github.com/henricm/ha-ferroamp/assets/33594610/6f7db717-d045-4872-a907-c615458828e3)
![mqtt explorer energyhub](https://github.com/henricm/ha-ferroamp/assets/33594610/419cc0ae-a010-43af-b2c6-d13b02737914)

**Comment by argoyle** [comment]
Hmmm, it looks like your custom config is not being used. My Mosquitto logs says this on restart:
<img width="616" alt="image" src="https://github.com/henricm/ha-ferroamp/assets/328334/5aabdd05-2da4-49ff-aa4e-42ed84ad96fb">

My config is in `share/mosquitto/energyhub.conf` and looks like this:
```
connection energyhub
address 192.168.1.97
remote_username extapi
remote_password superSecretPassword
topic extapi/# both
```

**Comment by Moogels** [comment]
It was somehow solved by turning off NGIX proxy manager add on :) Thx!!

**Comment by argoyle** [comment]
Nice! Closing this then.
