### ISSUE TITLE
Any way to control EV/OCPP?

### ISSUE THREAD

**Issue by fekberg** [henricm/ha-ferroamp#445]
Is it possible to send start/stop requests for charging an EV when EnergyHub is used as the OCPP server?

Given that Ferroamp is increasingly adding support for new chargers to connect to their OCPP, I would assume they added support to control it as well. Have you seen anything around this?

**Comment by argoyle** [comment]
Nopes, MQTT API hasn't been updated (at least officially) since 2021. You can download the specification here: https://ferroamp.com/support/nedladdningsbart/ if you click the `EnergyCloud & API:er` button.
