### ISSUE TITLE
Minor features

### ISSUE THREAD

**Issue by danielolsson100** [henricm/ha-ferroamp#5]
Really nice work ! Thanx for sharing this!
I'll try to help you with the development of this module in the future if needed.

I found some minor features
no icon: 
Apparent power
ESO 19110078 State of Charge

Name change?: 
ESM %ID% SOH to ESM %ID% State of Health

Sensor value: Unknown
System State of Charge
System State of Health
Total rated capacity of all batteries
![ferroamp](https://user-images.githubusercontent.com/35651684/85828676-3ec93e00-b789-11ea-91ce-7c799cfb740a.PNG)

**Comment by henricm** [comment]
Thanks! And thanks for the feedback.
Regarding the unknown sensors, I think this is because there's no values coming from Ferroamp API for these although they are described in the API docs. If so, they should probably be removed.

**Comment by danielolsson100** [comment]
I think that the "unknown" sensor values is somehow related to the timing of data from the MQTT input.
because there is data in the database from time to time.
I can see unknown and correct values if I run the following T-SQL [SELECT * FROM states where entity_id like '%system_state_of%'] from from SQL Lite Web addon to HA.
(I have also your nice work with this sensor addon to the facebook group: https://www.facebook.com/groups/Ferroamp.Club.Sweden.)

**Comment by argoyle** [comment]
I think all those points are resolved by #10 since I changed so the entities are restoring their state at startup

**Comment by argoyle** [comment]
Closing since #10 is merged
