### ISSUE TITLE
Clean up of the instruction to install

### ISSUE THREAD

**Issue by Letalis** [henricm/ha-ferroamp#57]
Hi,
I got several issues after applying the 2021.8 update.
And the Ferroamp integration doesn't work anymore.

And when I cleaned out the custom_component and follows your guide it doesn't match

**Comment by Letalis** [comment]
I cant start listening and are getting info in the MQTT broker , But no entities are displayed in HA

**Comment by Letalis** [comment]
Now it found everything.. Quite slow.. Not sure if its my environment or something else.

**Comment by argoyle** [comment]
Depending on what hardware you have discovery can take up to a minute. Other than that it shouldn't be slow I would say.

**Comment by argoyle** [comment]
If there are things in the documentation that is incorrect we welcome a PR with updates. 😊

**Comment by argoyle** [comment]
Closing this for now since you got it running.
